/* Camera pool + deterministic, difficulty-aware round selection.
 *
 * The data ships baked into the bundle (src/cams.json), generated by
 * scripts/build-cams.mjs from the parent NYC-traffic-cam repo's POI
 * classifications. Each camera carries a `tier` (easy/medium/hard) derived
 * from a recognizability score (terciles), so the three modes draw from
 * balanced ~315-camera pools.
 *
 * Live frames load straight from nyctmc.org as <img> tags — no API key,
 * no backend, no CORS dance (display-only). */

import data from './cams.json';

export type Tier = 'easy' | 'medium' | 'hard';
export type Mode = Tier | 'daily';

export type Cam = {
  id: string;
  name: string | null;
  lat: number;
  lng: number;
  tier: Tier;
  scene: string | null;
  area: string | null;
  landmark: string | null;
};

type Payload = {
  generated_at: number;
  source_generated_at: number;
  count: number;
  tiers: Record<Tier, number>;
  cameras: Cam[];
};

const PAYLOAD = data as Payload;
export const ALL_CAMS: Cam[] = PAYLOAD.cameras;
export const CAMS_BY_ID = new Map(ALL_CAMS.map((c) => [c.id, c]));
export const TIER_COUNTS = PAYLOAD.tiers;
export const CAMERA_LIST_DATE = new Date(PAYLOAD.source_generated_at * 1000);

export const NYCTMC_IMG = (id: string, t: number) =>
  `https://webcams.nyctmc.org/api/cameras/${id}/image?t=${t}`;

// FNV-1a 32-bit — cheap, well-spread deterministic hash for seeded picks.
export function hash(seed: string, n: number): number {
  let h = 2166136261;
  const s = `${seed}:${n}`;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function randomSeed(): string {
  return Math.random().toString(36).slice(2, 8).toUpperCase();
}

function poolFor(mode: Mode): Cam[] {
  if (mode === 'daily') return ALL_CAMS; // daily mixes every tier for variety
  return ALL_CAMS.filter((c) => c.tier === mode);
}

/* Pick N distinct cameras deterministically from a mode's pool. Same seed +
 * mode always yields the same cameras, which is what makes a shared link
 * reproducible without pinning IDs on the server. */
export function pickCams(seed: string, mode: Mode, n = 5): Cam[] {
  const pool = poolFor(mode);
  if (pool.length === 0) return [];
  const used = new Set<string>();
  const out: Cam[] = [];
  for (let i = 0; out.length < n && i < n * 12; i++) {
    const c = pool[hash(seed, out.length + i * 31) % pool.length];
    if (!c || used.has(c.id)) continue;
    used.add(c.id);
    out.push(c);
  }
  return out;
}

// Resolve a server-pinned challenge (list of UUIDs) back to Cam records,
// preserving order and dropping any the current pool no longer knows.
export function camsByIds(ids: string[]): Cam[] {
  const out: Cam[] = [];
  for (const id of ids) {
    const c = CAMS_BY_ID.get(id);
    if (c) out.push(c);
  }
  return out;
}

// Today's date in NYC (America/New_York) as YYYY-MM-DD — the daily seed.
export function nycDateStr(d = new Date()): string {
  // en-CA gives ISO-ish YYYY-MM-DD; the timeZone does the heavy lifting.
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: 'America/New_York',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(d);
}

export function dailySeed(d = new Date()): string {
  return `DAILY-${nycDateStr(d)}`;
}
